import { useState } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import { useFarmerDemo } from '../../../demo/farmerContext'
import { centreById,recommendation,stageKeys,type Stage,type Notice } from '../../../demo/farmerModel'
import { useLanguage } from '../../../i18n/languageState'
import { Button } from '../../../components/ui/Primitives'
import { WorkflowHeader } from './Common'
const stages:Stage[]=['booked','checkedIn','quality','weighing','complete']
export function BookingsPage(){
 const {state,update}=useFarmerDemo();const {t}=useLanguage();const [params]=useSearchParams();const [filter,setFilter]=useState('all');const [cancel,setCancel]=useState(false)
 const booking=state.bookings.find(b=>b.id===params.get('booking'))
 const list=state.bookings.filter(b=>filter==='all'||filter==='upcoming'&&b.stage==='booked'||filter==='active'&&['checkedIn','quality','weighing'].includes(b.stage)||filter==='past'&&['complete','cancelled'].includes(b.stage))
 return <><WorkflowHeader title="myBookings"/>{params.get('confirmed')&&booking&&<p className="wf-success" role="status">✓ {t('wfConfirmed')} · {booking.token}</p>}{booking?<section className="card wf-form"><h2>{booking.token} · {booking.id}</h2><p>{t(stageKeys[booking.stage])}</p><dl className="wf-facts"><div><dt>{t('commodity')}</dt><dd>{t(booking.commodity==='paddy'?'paddy':'wfCopra')}</dd></div><div><dt>{t('wfQuantity')}</dt><dd>{booking.quantity} kg</dd></div><div><dt>{t('centres')}</dt><dd>{centreById(booking.centreId)?.name}</dd></div><div><dt>{t('appointment')}</dt><dd>{booking.date} · {booking.slot}</dd></div>{booking.group&&<><div><dt>{t('wfGroupName')}</dt><dd>{booking.group.name}</dd></div><div><dt>{t('wfMembers')}</dt><dd>{booking.group.farmers}</dd></div><div><dt>{t('wfContact')}</dt><dd>{booking.group.contact}</dd></div></>}</dl><div className="wf-actions"><Link className="button" to={`/farmer/status?booking=${booking.id}`}>{t('liveStatus')}</Link><Link className="button secondary" to="/farmer/bookings">{t('myBookings')}</Link>{booking.stage==='booked'&&<Button className="secondary" onClick={()=>setCancel(!cancel)}>{t(cancel?'wfBack':'wfCancel')}</Button>}</div>{cancel&&booking.stage==='booked'&&<Button onClick={()=>{update(s=>({...s,nextId:s.nextId+1,bookings:s.bookings.map(b=>b.id===booking.id&&b.stage==='booked'?{...b,stage:'cancelled'}:b),notifications:[{id:`N${s.nextId}`,kind:'cancelled',reference:booking.token,read:false},...s.notifications]}));setCancel(false)}}>{t('wfCancelConfirm')}</Button>}</section>:<><label className="wf-field">{t('wfSort')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('wfAll')}</option><option value="upcoming">{t('wfUpcoming')}</option><option value="active">{t('wfActive')}</option><option value="past">{t('wfPast')}</option></select></label><div className="wf-grid">{list.map(b=><Link className="card wf-booking-link" key={b.id} to={`/farmer/bookings?booking=${b.id}`}><h2>{b.token} {b.group&&`· ${t('groupBooking')}`}</h2><p>{centreById(b.centreId)?.name}</p><p>{t(b.commodity==='paddy'?'paddy':'wfCopra')} · {b.quantity} kg</p><p>{b.date} · {b.slot}</p><strong>{t(stageKeys[b.stage])} →</strong></Link>)}</div>{!list.length&&<p>{t('wfEmpty')}</p>}<Link className="button" to="/farmer/services/book-slot">{t('bookSlot')}</Link></>}</>
}
export function LiveStatus(){
 const {state,update}=useFarmerDemo();const {t}=useLanguage();const [params,setParams]=useSearchParams()
 const booking=state.bookings.find(b=>b.id===params.get('booking'))||state.bookings.find(b=>!['complete','cancelled'].includes(b.stage))||state.bookings[0]
 if(!booking)return <><WorkflowHeader title="liveStatus"/><p>{t('wfEmpty')}</p><Link className="button" to="/farmer/services/book-slot">{t('bookSlot')}</Link></>
 const centre=recommendation(state,booking.commodity).find(c=>c.id===booking.centreId)!
 const held=!!state.staff?.held.includes(booking.id);const index=stages.indexOf(booking.stage);const done=['complete','cancelled'].includes(booking.stage)
 const ahead=done?0:Math.max(0,centre.queue-index*2);const wait=done?0:Math.ceil(ahead*centre.service/centre.capacity)+centre.penalty
 return <><WorkflowHeader title="liveStatus"/><label className="wf-field">{t('myBookings')}<select value={booking.id} onChange={e=>setParams({booking:e.target.value})}>{state.bookings.map(b=><option key={b.id} value={b.id}>{b.token} · {t(stageKeys[b.stage])}</option>)}</select></label><section className="card wf-form"><div className="fh-section-top"><h2>{booking.token}</h2><strong>{t(held?'stHeld':stageKeys[booking.stage])}</strong></div><p>{centre.name}</p><dl className="wf-facts"><div><dt>{t('wfPosition')}</dt><dd>{done?'—':ahead+1}</dd></div><div><dt>{t('wfAhead')}</dt><dd>{ahead}</dd></div><div><dt>{t('currentWait')}</dt><dd>{wait} {t('minutes')}</dd></div></dl><p>{t('wfWaitNotice')}</p><ol className="wf-progress">{stages.map((stage,i)=><li key={stage} className={!done&&i<=index||booking.stage==='complete'?'reached':''} aria-current={stage===booking.stage?'step':undefined}>{t(stageKeys[stage])}</li>)}</ol><div className="wf-actions">{!done&&!held&&<Button onClick={()=>update(s=>{const current=s.bookings.find(b=>b.id===booking.id)!;const next=stages[Math.min(4,stages.indexOf(current.stage)+1)];return {...s,nextId:s.nextId+1,bookings:s.bookings.map(b=>b.id===booking.id?{...b,stage:next}:b),notifications:[{id:`N${s.nextId}`,kind:next==='complete'?'completed':'queue',reference:booking.token,read:false},...s.notifications]}})}>{t('wfAdvance')}</Button>}<Button className="secondary" onClick={()=>update(s=>({...s,nextId:s.nextId+1,disruptions:{...s.disruptions,[centre.id]:!s.disruptions[centre.id]},notifications:[{id:`N${s.nextId}`,kind:'delay',reference:centre.name,read:false},...s.notifications]}))}>{t('wfToggleDelay')}</Button></div><p className="wf-demo">{centre.disrupted?t('wfDisrupted'):t('onSchedule')}</p></section></>
}
const noticeKeys:Record<Notice['kind'],'wfConfirmed'|'wfReminder'|'wfUpdate'|'wfDisrupted'|'wfComplete'|'wfAcknowledged'|'wfCancelled'>={confirmed:'wfConfirmed',reminder:'wfReminder',queue:'wfUpdate',delay:'wfDisrupted',completed:'wfComplete',grievance:'wfAcknowledged',cancelled:'wfCancelled'}
export function NotificationsPage(){const {state,update}=useFarmerDemo();const {t}=useLanguage();return <><WorkflowHeader title="notificationLabel"/>{!state.notifications.length&&<p>{t('wfEmpty')}</p>}<div className="wf-notices">{state.notifications.map(n=><article key={n.id} className={`card ${n.read?'wf-read':''}`}><h2>{t(noticeKeys[n.kind])}</h2><p>{n.reference}</p><Button className="secondary" onClick={()=>update(s=>({...s,notifications:s.notifications.map(item=>item.id===n.id?{...item,read:!item.read}:item)}))}>{t(n.read?'wfUnread':'wfRead')}</Button></article>)}</div></>}



