import { centreLabel } from '../useFarmerLanguage'
import { useState } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import { useFarmerDemo } from '../../../demo/farmerContext'
import { recommendation } from '../../../demo/farmerModel'
import { useFarmerLanguage as useLanguage } from '../useFarmerLanguage'
import { WorkflowHeader,CommoditySelect } from './Common'
export function CentreDiscovery({detail=false}:{detail?:boolean}) {
 const {state,update}=useFarmerDemo();const {t}=useLanguage();const [sort,setSort]=useState('total');const [params]=useSearchParams()
 const ranked=recommendation(state);const selected=ranked.find(c=>c.id===(params.get('centre')||state.centreId))||ranked[0]
 const list=detail?[selected]:[...ranked].sort((a,b)=>sort==='distance'?a.distance-b.distance:a.total-b.total)
 return <><WorkflowHeader title={detail?'viewCentre':'findCentre'}/><p className="muted">{t('location')}</p><div className="wf-form-grid"><CommoditySelect value={state.commodity} onChange={commodity=>update(s=>({...s,commodity}))}/>{!detail&&<label className="wf-field">{t('wfSort')}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="total">{t('wfTotal')}</option><option value="distance">{t('wfDistance')}</option></select></label>}</div><div className="wf-grid">{list.map(c=><section className="card wf-centre" key={c.id}><div className="fh-section-top"><h2>{centreLabel(c.name || '')}</h2>{c.id===ranked[0].id&&<span className="fh-status">✓ {t('bestOption')}</span>}</div><p>{c.distance} {t('kilometres')} · {c.area}</p><dl className="wf-facts"><div><dt>{t('travel')}</dt><dd>{c.travel} {t('minutes')}</dd></div><div><dt>{t('currentWait')}</dt><dd>{c.wait+c.penalty} {t('minutes')}</dd></div><div><dt>{t('wfQueue')}</dt><dd>{c.queue}</dd></div><div><dt>{t('wfCapacity')}</dt><dd>{c.capacity} / {c.resources}</dd></div><div><dt>{t('wfTotal')}</dt><dd><strong>{c.total} {t('minutes')}</strong></dd></div></dl><p>{c.disrupted?t('wfDisrupted'):t('onSchedule')} · {c.commodities.map(x=>t(x==='paddy'?'paddy':'wfCopra')).join(', ')}</p><details className="wf-details"><summary>{t('wfWhy')}</summary><p>{t('wfTotal')} = {t('travel')} ({c.travel}) + {t('currentWait')} ({c.wait}) + {t('wfService')} ({c.service}) + {t('wfPenalty')} ({c.penalty}) = {c.total} {t('minutes')}.</p><p>{t('vReason')}</p></details><div className="wf-actions"><Link className="button" to={`/farmer/services/book-slot?centre=${c.id}`} onClick={()=>update(s=>({...s,centreId:c.id}))}>{t('bookSlot')}</Link>{!detail&&<Link className="button secondary" to={`/farmer/services/centre-details?centre=${c.id}`}>{t('viewCentre')}</Link>}</div>{detail&&<p>Operational stages: quality inspection, weighing and unloading. {c.resources} parallel processing resource(s) are considered in this comparison.</p>}</section>)}</div></>
}
