import { useState,type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useFarmerLanguage as useLanguage, centreLabel } from '../useFarmerLanguage'
import { languages,isLanguage } from '../../../i18n/translations'
import { useFarmerDemo } from '../../../demo/farmerContext'
import { useDemoAuth } from '../../../auth/authState'
import { demoLoginFarmer } from '../../../data/demoData'
import { workflowCentres,chatQuestions,demoSchemes,guideSections,workflowPrices } from '../../../data/workflowData'
import { validateRequired } from '../../../utils/validation'
import { Button } from '../../../components/ui/Primitives'
import { WorkflowHeader } from './Common'
import { FarmerLogout } from '../FarmerLogout'
export function GrievanceForm(){const {state,update}=useFarmerDemo();const {t}=useLanguage();const [category,setCategory]=useState('bookings');const [reference,setReference]=useState('');const [description,setDescription]=useState('');const [error,setError]=useState(false);const [receipt,setReceipt]=useState('')
 function submit(e:FormEvent){e.preventDefault();if(description.trim().length<10||description.length>500){setError(true);return}let id='';update(s=>{id=`GR-${s.nextId}`;return {...s,nextId:s.nextId+1,grievances:[{id,category,reference,description:description.trim(),status:'submitted'},...s.grievances],notifications:[{id:`N${s.nextId}`,kind:'grievance',reference:id,read:false},...s.notifications]}});setReceipt(id);setDescription('');setError(false)}
 return <><WorkflowHeader title="grievance"/><form className="card wf-form" onSubmit={submit}><label className="wf-field">{t('wfCategory')}<select value={category} onChange={e=>setCategory(e.target.value)}><option value="bookings">{t('myBookings')}</option><option value="centre">{t('centres')}</option><option value="quality">{t('wfQuality')}</option><option value="other">{t('more')}</option></select></label><label className="wf-field">{t('wfReference')}<select value={reference} onChange={e=>setReference(e.target.value)}><option value="">—</option>{workflowCentres.map(c=><option key={c.id} value={c.id}>{centreLabel(c.name)}</option>)}{state.bookings.map(b=><option key={b.id} value={b.id}>{b.token} · {b.centreId}</option>)}</select></label><label className="wf-field">{t('wfDescription')}<textarea value={description} maxLength={500} onChange={e=>setDescription(e.target.value)}/></label>{error&&<p role="alert" className="auth-error">{t('wfInvalid')}</p>}<Button type="submit">{t('wfSubmit')}</Button>{receipt&&<p role="status" className="wf-success">{receipt} · {t('wfSubmitted')}</p>}</form><h2>{t('wfHistory')}</h2>{!state.grievances.length&&<p>{t('wfEmpty')}</p>}{state.grievances.map(g=><article className="card" key={g.id}><h3>{g.id} · {t('wfSubmitted')}</h3><p>{g.reference}</p><p>{g.description}</p></article>)}</>
}
export function ChatPage(){const {t}=useLanguage();const [input,setInput]=useState('');const [messages,setMessages]=useState<{question:string;answer:string;route?:string}[]>([])
 function send(question:string,index?:number){if(!validateRequired(question))return;const found=index??chatQuestions.findIndex(q=>t(q.key).toLocaleLowerCase()===question.trim().toLocaleLowerCase());const reply=chatQuestions[found];setMessages(m=>[...m,{question,answer:reply?.answer||'Please choose a suggested question below, or visit Support for help.',route:reply?.route||'/farmer/services/support'}]);setInput('')}
 return <><WorkflowHeader title="chat"/><p>{t('wfScripted')}</p><div className="wf-chat" role="log" aria-live="polite">{messages.map((m,i)=><article key={i}><p className="wf-chat-question">{m.question}</p><p>{m.answer}</p><Link className="fh-text-link" to={m.route!}>{t('wfNext')} →</Link></article>)}</div><div className="wf-actions">{chatQuestions.map((q,i)=><Button key={q.key} className="secondary" onClick={()=>send(t(q.key),i)}>{t(q.key)}</Button>)}</div><form className="wf-form" onSubmit={e=>{e.preventDefault();send(input)}}><label className="wf-field">{t('wfMessage')}<input value={input} maxLength={200} onChange={e=>setInput(e.target.value)}/></label><Button type="submit" disabled={!validateRequired(input)}>{t('wfSend')}</Button></form></>
}
export function InformationPage({kind}:{kind:string}){const {t}=useLanguage();
 if(kind==='prices'||kind==='market')return <><WorkflowHeader title={kind==='prices'?'prices':'market'}/><p className="muted">Reference amounts only; these are not current market quotations or official MSP. Confirm the applicable rate with your procurement centre.</p><div className="wf-grid">{workflowPrices.map(p=><section className="card" key={p.commodity}><h2>{t(p.commodity==='paddy'?'paddy':'wfCopra')}</h2><p className="metric">₹{p.rate.toFixed(2)} / kg</p><p>{kind==='prices'?'Reference procurement amount. Verify the current rate with the procurement agency.':'Keep produce dry and compare centre waiting times before travelling. Live market updates are not connected.'}</p><Link className="fh-text-link" to="/farmer/services/find-centre">{t('findCentre')} →</Link></section>)}</div></>
 if(kind==='schemes')return <><WorkflowHeader title="schemes"/><p>Support topics to discuss with your centre. Current government scheme listings and eligibility checks are not connected.</p>{demoSchemes.map(s=><details className="card wf-details" key={s.title}><summary>{s.title}</summary><p>{s.text}</p><p>{s.documents}</p><Link className="fh-text-link" to="/farmer/services/support">{t('support')}</Link></details>)}</>
 if(kind==='guide')return <><WorkflowHeader title="guide"/>{guideSections.map((g,i)=><details className="card wf-details" key={g.title}><summary>{i+1}. {g.title}</summary><p>{g.text}</p></details>)}</>
 return <><WorkflowHeader title="support"/><section className="card"><h2>{t('support')}</h2><p>Use guided questions for help, or save a grievance on this device. A live helpline and external grievance submission are not connected.</p><div className="wf-actions"><Link className="button" to="/farmer/services/chat">{t('chat')}</Link><Link className="button secondary" to="/farmer/services/grievance">{t('grievance')}</Link></div></section>{chatQuestions.map(q=><details className="card wf-details" key={q.key}><summary>{t(q.key)}</summary><p>{q.answer}</p><Link className="fh-text-link" to={q.route}>{t('wfNext')} →</Link></details>)}</>
}
export function SettingsPage({profile=false}:{profile?:boolean}){const {state,update}=useFarmerDemo();const {language,setLanguage,t}=useLanguage();const {state:session}=useDemoAuth();return <><WorkflowHeader title={profile?'profileDetails':'settings'}/><section className="card wf-form"><div className="pf-profile-summary"><span className="fh-avatar" aria-hidden="true">RK</span><div><h2>{session.status==='active'?session.session.displayName:demoLoginFarmer.name}</h2><p>{t('farmer')} · {t('location')}</p></div></div><label className="wf-field">{t('language')}<select value={language} onChange={e=>{if(isLanguage(e.target.value))setLanguage(e.target.value)}}>{languages.map(l=><option key={l.code} value={l.code}>{l.label}</option>)}</select></label><label className="wf-toggle"><input type="checkbox" checked={state.notificationsEnabled} onChange={e=>update(s=>({...s,notificationsEnabled:e.target.checked}))}/>{t('wfPreference')}</label><div className="wf-actions"><Link className="button secondary" to="/farmer/bookings">{t('myBookings')} · {state.bookings.filter(b=>!['complete','cancelled'].includes(b.stage)).length}</Link><Link className="fh-text-link" to="/farmer/bookings?view=history">{t('vHistory')}</Link><Link className="fh-text-link" to="/farmer/services/support">{t('support')}</Link><Link className="fh-text-link" to="/">{t('vPublic')}</Link></div><FarmerLogout/></section></>}

