import { useState } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import { useLanguage } from '../../i18n/languageState'
import { dateOffset,type Booking } from '../../demo/farmerModel'
import { changeQueue } from '../../demo/staffOperations'
import { farmers,demoLoginFarmer } from '../../data/demoData'
import { Button } from '../../components/ui/Primitives'
import { bookingStatus,useOperations } from './staffView'
export function StaffBookingActions({booking}:{booking:Booking}){const {staff,update}=useOperations();const {t}=useLanguage();if(['complete','cancelled'].includes(booking.stage))return null;const held=staff.held.includes(booking.id);return <div className="wf-actions">{held?<Button onClick={()=>update(s=>changeQueue(s,booking.id,'resume'))}>{t('stResume')}</Button>:<><Button onClick={()=>update(s=>changeQueue(s,booking.id,booking.stage==='booked'?'checkIn':booking.stage==='weighing'?'complete':'advance'))}>{t(booking.stage==='booked'?'stCheckIn':booking.stage==='weighing'?'stComplete':'stAdvance')}</Button><Button className="secondary" onClick={()=>update(s=>changeQueue(s,booking.id,'hold'))}>{t('stHold')}</Button></>}</div>}
export function StaffBookings({mode='bookings'}:{mode?:'bookings'|'queue'|'groups'}){
 const {bookings,staff,estimate}=useOperations();const {t}=useLanguage();const [params]=useSearchParams();const [filter,setFilter]=useState('all');const detail=bookings.find(b=>b.id===params.get('booking'))
 const list=bookings.filter(b=>(mode!=='groups'||b.group)&&(!params.get('stage')||b.stage===params.get('stage'))&&(filter==='all'||filter==='today'&&b.date===dateOffset(0)||filter==='upcoming'&&b.stage==='booked'&&b.date>dateOffset(0)||filter==='past'&&['complete','cancelled'].includes(b.stage)))
 return <><h1>{t(mode==='queue'?'stQueue':mode==='groups'?'groupBooking':'myBookings')}</h1>{detail?<section className="card st-detail"><h2>{detail.token} · {detail.id}</h2><p>{demoLoginFarmer.name} · {t(bookingStatus(detail,staff.held))}</p><dl className="wf-facts"><div><dt>{t('commodity')}</dt><dd>{t(detail.commodity==='paddy'?'paddy':'wfCopra')}</dd></div><div><dt>{t('wfQuantity')}</dt><dd>{detail.quantity} kg</dd></div><div><dt>{t('appointment')}</dt><dd>{detail.date} · {detail.slot}</dd></div>{detail.group&&<><div><dt>{t('wfGroupName')}</dt><dd>{detail.group.name}</dd></div><div><dt>{t('wfContact')}</dt><dd>{detail.group.contact}</dd></div><div><dt>{t('wfMembers')}</dt><dd>{detail.group.farmers}</dd></div></>}</dl><StaffBookingActions booking={detail}/><Link to={'/staff/'+mode}>{t('wfBack')}</Link></section>:<><label className="wf-field st-filter">{t('wfSort')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('wfAll')}</option><option value="today">{t('stToday')}</option><option value="upcoming">{t('wfUpcoming')}</option><option value="past">{t('wfPast')}</option></select></label>{params.get('stage')&&<Link to="/staff/queue">{t('wfAll')}</Link>}<div className="st-table" role="region" aria-label={t('myBookings')} tabIndex={0}><table><thead><tr>{['tokenLabel','farmer','commodity','appointment','wfPosition','currentWait','stPriority','operations'].map(key=><th key={key}>{t(key as 'farmer')}</th>)}</tr></thead><tbody>{list.map((b,i)=>{const done=['complete','cancelled'].includes(b.stage);return <tr key={b.id}><td>{b.token}{b.group&&<p>{b.group.name} · {b.group.farmers} {t('farmer')} · {b.group.contact}</p>}</td><td>{demoLoginFarmer.name}</td><td>{t(b.commodity==='paddy'?'paddy':'wfCopra')} · {b.quantity} kg</td><td>{b.date}<br/>{b.slot}</td><td>{done?'—':i+1}</td><td>{done?0:estimate.wait+estimate.penalty} {t('minutes')}</td><td>{t(bookingStatus(b,staff.held))}<br/>{t('stNormal')}</td><td><Link to={'/staff/'+mode+'?booking='+b.id}>{t('stInspect')}</Link><StaffBookingActions booking={b}/></td></tr>})}</tbody></table></div>{!list.length&&<p>{t('wfEmpty')}</p>}</>}</>
}
export function StaffFarmers(){const {state,bookings,staff}=useOperations();const {t}=useLanguage();const [search,setSearch]=useState('');const [params]=useSearchParams();const records=[demoLoginFarmer,...farmers];const selected=records.find(f=>f.id===params.get('farmer'));return <><h1>{t('stFarmers')}</h1>{selected?<section className="card st-detail"><h2>{selected.name}</h2><p>{selected.id} · {selected.village}, {selected.district}</p><p>{t('sampleProfile')}</p><h3>{t('myBookings')}</h3>{selected.id===demoLoginFarmer.id?bookings.map(b=><p key={b.id}><Link to={'/staff/bookings?booking='+b.id}>{b.token} · {t(bookingStatus(b,staff.held))}</Link></p>):<p>{t('wfEmpty')}</p>}<h3>{t('grievance')}</h3>{selected.id===demoLoginFarmer.id&&state.grievances.map(g=><details key={g.id}><summary>{g.id} · {t('wfSubmitted')}</summary><p>{g.reference} · {g.description}</p></details>)}<Link to="/staff/farmers">{t('wfBack')}</Link></section>:<><label className="wf-field st-filter">{t('stSearch')}<input value={search} maxLength={60} onChange={e=>setSearch(e.target.value)}/></label><div className="wf-grid">{records.filter(f=>(f.name+' '+f.id+' '+f.district).toLowerCase().includes(search.toLowerCase())).map(f=><Link className="card" to={'/staff/farmers?farmer='+f.id} key={f.id}><h2>{f.name}</h2><p>{f.id} · {f.village}</p><p>{t('stInspect')} →</p></Link>)}</div></>}</>}
