import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useLanguage } from '../../i18n/languageState'
import { stageKeys,type Notice } from '../../demo/farmerModel'
import { useOperations } from './staffView'
import { Button } from '../../components/ui/Primitives'
const noticeKeys={confirmed:'wfConfirmed',reminder:'wfReminder',queue:'wfUpdate',delay:'wfDisrupted',completed:'wfComplete',grievance:'wfAcknowledged',cancelled:'wfCancelled'} as const satisfies Record<Notice['kind'],string>
export function StaffMessages(){const {state,staff,estimate,update}=useOperations();const {t}=useLanguage();const notices=[{id:'shift-announcement',title:t('stAnnouncement'),text:'Demo shift: verify the token and produce details at arrival. Report equipment issues before advancing work.'},...(estimate.queue>=6?[{id:'queue-threshold-'+staff.centreId,title:t('stThreshold'),text:`${estimate.name} · ${estimate.queue} · ${t('wfQueue')}`}]:[]),...state.notifications.map(n=>({id:n.id,title:t(noticeKeys[n.kind]),text:n.reference}))];return <><h1>{t('stMessages')}</h1><div className="st-inbox">{notices.map(n=><article className={'card '+(staff.read.includes(n.id)?'st-read':'')} key={n.id}><h2>{n.title}</h2><p>{n.text}</p><Button className="secondary" onClick={()=>update(s=>{const latest=s.staff||staff;return {...s,staff:{...latest,read:latest.read.includes(n.id)?latest.read.filter(id=>id!==n.id):[...latest.read,n.id]}}})}>{t(staff.read.includes(n.id)?'wfUnread':'wfRead')}</Button></article>)}</div></>}
export function StaffReports(){const {bookings,resources,estimate}=useOperations();const {t}=useLanguage();const [date,setDate]=useState('');const [commodity,setCommodity]=useState('all');const [status,setStatus]=useState('all');const list=bookings.filter(b=>(!date||b.date===date)&&(commodity==='all'||b.commodity===commodity)&&(status==='all'||b.stage===status));const completed=list.filter(b=>b.stage==='complete');return <><h1>{t('stReports')}</h1><div className="st-filters"><label className="wf-field">{t('wfDate')}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="wf-field">{t('commodity')}<select value={commodity} onChange={e=>setCommodity(e.target.value)}><option value="all">{t('wfAll')}</option><option value="paddy">{t('paddy')}</option><option value="copra">{t('wfCopra')}</option></select></label><label className="wf-field">{t('stPriority')}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('wfAll')}</option>{Object.entries(stageKeys).map(([key,label])=><option key={key} value={key}>{t(label)}</option>)}</select></label><Button className="secondary" onClick={()=>{setDate('');setCommodity('all');setStatus('all')}}>{t('wfAll')}</Button></div><div className="st-table"><table><thead><tr><th>{t('myBookings')}</th><th>{t('wfComplete')}</th><th>{t('stThroughput')}</th><th>{t('currentWait')}</th><th>{t('stDisruptions')}</th></tr></thead><tbody><tr><td>{list.length}</td><td>{completed.length}</td><td>{completed.reduce((sum,b)=>sum+b.quantity,0)}</td><td>{estimate.wait+estimate.penalty} {t('minutes')}</td><td>{resources.active.length}</td></tr></tbody></table></div><p>Booking totals follow the filters. Wait and disruption figures are the selected centre’s current demo snapshot, not historical measurements.</p>{list.map(b=><p key={b.id}><Link to={'/staff/bookings?booking='+b.id}>{b.token} · {b.date} · {b.quantity} kg · {t(stageKeys[b.stage])}</Link></p>)}{!list.length&&<p>{t('wfEmpty')}</p>}</>}
