import { useState,type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useLanguage } from '../../i18n/languageState'
import { maxDigits } from '../../utils/validation'
import { reportDisruption,resolveDisruption } from '../../demo/staffOperations'
import type { ResourceType,OperationalDisruption } from '../../demo/staffResources'
import { Button } from '../../components/ui/Primitives'
import { resourceKeys,useOperations } from './staffView'
export function StaffDisruptions(){const {staff,state,resources,estimate,update}=useOperations();const {t}=useLanguage();const [type,setType]=useState<ResourceType>('quality');const [severity,setSeverity]=useState<OperationalDisruption['severity']>('medium');const [recovery,setRecovery]=useState('30');const [note,setNote]=useState('');const [error,setError]=useState<'stInvalid'|'stNoResource'|null>(null);const [receipt,setReceipt]=useState('')
 function submit(e:FormEvent){e.preventDefault();let id='';let problem:typeof error=null;update(s=>{try{const next=reportDisruption(s,{centreId:staff.centreId,type,severity,recovery:Number(recovery),note:note.trim()});id=next.staff!.incidents[0].id;return next}catch(err){problem=err instanceof Error&&err.message==='stNoResource'?'stNoResource':'stInvalid';return s}});setError(problem);if(!problem){setReceipt(id);setNote('')}}
 return <><h1>{t('stDisruptions')}</h1><p className="st-alert">{t('stQuality')}: {resources.available.quality}/2 · {t('currentWait')}: {estimate.wait+estimate.penalty} {t('minutes')}</p>{state.disruptions[staff.centreId]&&<section className="card"><p>{t('wfDisrupted')} · P3 demo delay</p><Button onClick={()=>update(s=>({...s,disruptions:{...s.disruptions,[staff.centreId]:false}}))}>{t('stResolve')}</Button></section>}<form className="card wf-form" onSubmit={submit} noValidate><label className="wf-field">{t('stResource')}<select value={type} onChange={e=>setType(e.target.value as ResourceType)}>{Object.entries(resourceKeys).map(([value,key])=><option key={value} value={value}>{t(key)}</option>)}</select></label><label className="wf-field">{t('stSeverity')}<select value={severity} onChange={e=>setSeverity(e.target.value as typeof severity)}><option value="low">{t('stLow')}</option><option value="medium">{t('stMedium')}</option><option value="high">{t('stHigh')}</option></select></label><label className="wf-field">{t('stRecovery')}<input inputMode="numeric" maxLength={3} value={recovery} onChange={e=>setRecovery(maxDigits(e.target.value,3))}/></label><label className="wf-field">{t('stNote')}<textarea maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{t(error)}</p>}<Button type="submit">{t('stReport')}</Button>{receipt&&<p role="status">{receipt} · {t('wfSubmitted')}</p>}</form><h2>{t('wfHistory')}</h2>{staff.incidents.filter(d=>d.centreId===staff.centreId).map(d=><section className="card st-detail" key={d.id}><h3>{d.id} · {t(resourceKeys[d.type])} · {t(d.resolved?'stResolved':'wfActive')}</h3><p>{t(d.severity==='high'?'stHigh':d.severity==='medium'?'stMedium':'stLow')} · {d.recovery} {t('minutes')}</p><p>{d.note}</p>{!d.resolved&&<Button className="secondary" onClick={()=>update(s=>resolveDisruption(s,d.id))}>{t('stResolve')}</Button>}</section>)}</>
}
export function StaffHelp({profile=false}:{profile?:boolean}){const {t}=useLanguage();return <><h1>{t(profile?'stProfile':'help')}</h1>{profile?<section className="card"><h2>Anitha S.</h2><p>STF001 · {t('stInspector')}</p><p>Kollam Procurement Centre · Kollam East Demo Centre</p><p>{t('wfDemo')}</p><Link to="/staff/help">{t('help')}</Link></section>:<>{[['stQueue','Check in a token, advance through quality and weighing, then mark complete. Hold pauses progress; resume before continuing.','/staff/queue'],['stDisruptions','Report the unavailable resource, severity and recovery estimate. Resolve it when restored. Demo capacity and farmer wait react immediately.','/staff/disruptions'],['stMessages','Read local booking updates and operational alerts. No SMS or external message is sent.','/staff/messages']].map(([key,text,path])=><details className="card wf-details" key={key}><summary>{t(key as 'stQueue')}</summary><p>{text}</p><Link to={path}>{t('stInspect')} →</Link></details>)}<section className="card"><h2>{t('support')}</h2><p>Demo operations desk: Anitha S., Kollam Procurement Centre. Use the local Messages inbox for the sample shift announcement. No live helpline is connected.</p><Link to="/staff/messages">{t('stMessages')}</Link></section></>}</>}
