import { Link } from 'react-router-dom'
import { useLanguage } from '../../i18n/languageState'
import { dateOffset } from '../../demo/farmerModel'
import { resourceTotals } from '../../demo/staffResources'
import { useOperations,resourceKeys } from './staffView'
export function StaffDashboard({live=false}:{live?:boolean}){
 const {t}=useLanguage();const {bookings,resources,estimate}=useOperations();const today=bookings.filter(b=>b.date===dateOffset(0));const active=bookings.filter(b=>!['complete','cancelled'].includes(b.stage));const bottleneck=(Object.keys(resourceTotals) as (keyof typeof resourceTotals)[]).reduce((a,b)=>resources.available[b]/resourceTotals[b]<resources.available[a]/resourceTotals[a]?b:a,'quality')
 return <><h1>{t(live?'stLive':'stDashboard')}</h1>{(resources.active.length>0||estimate.disrupted)&&<p role="status" className="st-alert">{t('wfDisrupted')} · <Link to="/staff/disruptions">{t('stDisruptions')} →</Link></p>}<div className="st-metrics">{[[t('stProcessed'),bookings.filter(b=>b.stage==='complete'&&b.completedOn===dateOffset(0)).length],[t('stQueue'),active.length],[t('currentWait'),`${estimate.wait+estimate.penalty} ${t('minutes')}`],[t('stToday'),today.length],[t('stDisruptions'),resources.active.length+(estimate.disrupted&&!resources.active.length?1:0)]].map(([name,value])=><section className="card" key={name}><p>{name}</p><strong>{value}</strong></section>)}</div><section className="card"><h2>{t('resources')}</h2><div className="st-metrics">{Object.entries(resourceTotals).map(([type,total])=><div key={type}><p>{t(resourceKeys[type as keyof typeof resourceTotals])}</p><strong>{resources.available[type as keyof typeof resourceTotals]} / {total}</strong></div>)}</div></section><section className="card"><h2>{t('stBottleneck')}: {t(resourceKeys[bottleneck])}</h2><p>{t('wfCapacity')}: {resources.available[bottleneck]} · {t('wfQueue')}: {estimate.queue+active.length} · {t('currentWait')}: {estimate.wait+estimate.penalty} {t('minutes')}</p><p>Demo estimate: queued workload × service minutes ÷ effective resource capacity, plus disruption delay. The most constrained reported resource is shown; without an outage, quality inspection is the sample limiting stage.</p><Link className="button secondary" to="/staff/queue">{t('stInspect')}</Link></section><div className="st-stages">{[['booked','stArrival'],['checkedIn','wfCheckedIn'],['quality','wfQuality'],['weighing','wfWeighing'],['complete','wfComplete']].map(([stage,key])=><Link className="card" key={stage} to={'/staff/queue?stage='+stage}><h2>{t(key as 'stArrival')}</h2><strong>{bookings.filter(b=>b.stage===stage).length}</strong><p>{t('stInspect')} →</p></Link>)}</div></>
}


