import { Link } from 'react-router-dom'
import { Sprout, Warehouse, Building2, ArrowRight, Globe } from 'lucide-react'
import { languages, isLanguage } from '../i18n/translations'
import { useFarmerLanguage } from './farmer/useFarmerLanguage'
import { informationServices, servicePath } from './farmer/farmerServices'
import { ServiceCarousel } from './farmer/ServiceCarousel'
export default function LandingPage() {
 const {t,language,setLanguage}=useFarmerLanguage()
 return <div className="pf-public"><a className="skip-link" href="#main">{t('skip')}</a><header className="pf-public-header"><Link to="/" className="brand"><span className="brand-mark"><Sprout aria-hidden="true"/></span><span>ProcureFlow<small>{t('homeIntro')}</small></span></Link><label className="language"><Globe size={16} aria-hidden="true"/><select aria-label={t('language')} value={language} onChange={e=>{if(isLanguage(e.target.value))setLanguage(e.target.value)}}>{languages.map(l=><option value={l.code} key={l.code}>{l.label}</option>)}</select></label></header><main id="main" tabIndex={-1} className="pf-public-main"><div className="pf-public-intro"><p className="eyebrow">ProcureFlow · {t('farmerAccess')}</p><h1>{t('vPlan')}</h1></div><ServiceCarousel publicEntry/><section className="pf-role-section"><div className="fh-section-top"><h2>{t('vDiscover')}</h2><span>{t('location')}</span></div><div className="pf-roles">{[{key:'farmer',icon:Sprout,to:'/farmer/login',action:'bookSlot'},{key:'staff',icon:Warehouse,to:'/staff',action:'operations'},{key:'admin',icon:Building2,to:'/admin',action:'monitoring'}].map(({key,icon:Icon,to,action})=><Link className="pf-role" key={key} to={to}><Icon size={28} aria-hidden="true"/><div><h3>{t(key as 'farmer')}</h3><p>{t(action as 'bookSlot')}</p></div><ArrowRight size={20} aria-hidden="true"/></Link>)}</div></section><section className="pf-public-services" aria-label={t('quickInfo')}>{informationServices.map(({id,key,icon:Icon})=><Link key={id} to={servicePath(id)}><Icon size={25} aria-hidden="true"/><span>{t(key)}</span></Link>)}</section><section className="pf-public-note"><Sprout size={28} aria-hidden="true"/><div><h2>{t('vTogether')}</h2><p>{t('vReason')}</p></div></section></main><footer className="pf-public-footer"><strong>ProcureFlow</strong><Link to="/farmer/services/support">{t('support')} →</Link></footer></div>
}
