import { Link } from 'react-router-dom'
import { ArrowRight, Sprout, Warehouse, Building2, Clock3, Layers3, Accessibility, Check, MapPin } from 'lucide-react'
import { Header } from '../components/layout/AppShell'
import { Badge } from '../components/ui/Primitives'

const roles = [
  { title: 'Farmer', text: 'Book procurement, track your queue and know when to leave.', path: '/farmer/login', icon: Sprout, label: 'Plan your visit' },
  { title: 'Centre Staff', text: 'Manage arrivals, resources and procurement stages.', path: '/staff', icon: Warehouse, label: 'Open operations' },
  { title: 'Administrator', text: 'Monitor centre load, bottlenecks and network performance.', path: '/admin', icon: Building2, label: 'View the network' },
]
export default function LandingPage() {
  return <><Header /><main id="main" tabIndex={-1} className="landing"><section className="hero"><div><p className="eyebrow"><span className="small-rule" /> A better procurement day</p><h1>Reach the centre <br />when the centre is <em>ready for you.</em></h1><p className="hero-copy">Capacity-aware procurement scheduling, live queue guidance and end-to-end procurement tracking.</p><div className="hero-actions"><a className="button" href="#roles">Continue to Demo <ArrowRight size={18} aria-hidden="true" /></a><span className="prototype-label">SIH 2026 Prototype</span></div></div><div className="journey-illustration" aria-label="Procurement journey preview: plan your visit, arrive with guidance, track every stage"><div className="illustration-top"><Sprout size={25} aria-hidden="true" /><span>FROM FARM TO CENTRE</span></div><h2>A little planning.<br />A lot less waiting.</h2><div className="illustration-steps">{[{ icon: Check, title: 'Plan your visit', text: 'A window that works for the centre.' }, { icon: MapPin, title: 'Arrive with guidance', text: 'Know when it is time to leave.' }, { icon: Layers3, title: 'Track every stage', text: 'Clarity from arrival to completion.' }].map(({ icon: Icon, title, text }) => <div key={title}><span className="step-symbol"><Icon size={19} aria-hidden="true" /></span><span><strong>{title}</strong><small>{text}</small></span></div>)}</div><div className="field-lines" aria-hidden="true" /></div></section><section id="roles" className="role-section"><div className="section-heading"><div><p className="eyebrow">One connected experience</p><h2>Choose your workspace</h2></div><p className="muted">Explore the demo from your point of view.</p></div><div className="role-grid">{roles.map(({ title, text, path, icon: Icon, label }) => <Link className="role-card" to={path} key={path}><span className="icon-tile"><Icon size={26} aria-hidden="true" /></span><h3>{title}</h3><p>{text}</p><span className="role-action">{label}<ArrowRight size={18} aria-hidden="true" /></span></Link>)}</div></section><section className="principles" aria-label="System principles">{[{ title: 'Less waiting', text: 'Make the visit, not the queue, your priority.', icon: Clock3 }, { title: 'Capacity-aware', text: 'Plan around the resources that do the work.', icon: Layers3 }, { title: 'Accessible by design', text: 'Built with assisted access in mind.', icon: Accessibility }].map(({ title, text, icon: Icon }) => <div key={title}><Icon aria-hidden="true" size={23} /><span><h3>{title}</h3><p>{text}</p></span></div>)}</section></main><footer className="footer"><span>ProcureFlow</span><span>Thoughtfully planned. Fairly served.</span><Badge>SIH 2026 Prototype</Badge></footer></>
}


