"""backend foundation

Revision ID: 0001
Revises:
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centres',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('operating_status', sa.Enum('open', 'closed', 'suspended', name='operatingstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reference_travel_minutes', sa.Integer(), nullable=True),
    sa.Column('reference_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_centres_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_centres_longitude_range')),
    sa.CheckConstraint('reference_distance_km >= 0', name=op.f('ck_centres_distance_nonnegative')),
    sa.CheckConstraint('reference_travel_minutes >= 0', name=op.f('ck_centres_travel_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_centres')),
    sa.UniqueConstraint('code', name=op.f('uq_centres_code'))
    )
    op.create_table('commodities',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commodities')),
    sa.UniqueConstraint('code', name=op.f('uq_commodities_code'))
    )
    op.create_table('roles',
    sa.Column('name', sa.Enum('farmer', 'staff', 'centre_manager', 'delegate', 'district_admin', 'state_admin', 'super_admin', name='rolename', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('login_name', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login_name', name=op.f('uq_users_login_name')),
    sa.UniqueConstraint('mobile', name=op.f('uq_users_mobile'))
    )
    op.create_table('centre_commodities',
    sa.Column('centre_id', sa.String(length=36), nullable=False),
    sa.Column('commodity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_centre_commodities_centre_id_centres')),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], name=op.f('fk_centre_commodities_commodity_id_commodities')),
    sa.PrimaryKeyConstraint('centre_id', 'commodity_id', name=op.f('pk_centre_commodities'))
    )
    op.create_table('centre_resources',
    sa.Column('centre_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.Enum('gate', 'quality_desk', 'weighbridge', 'staff', 'other', name='resourcetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('total_count >= 0 AND active_count >= 0 AND active_count <= total_count', name=op.f('ck_centre_resources_valid_counts')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_centre_resources_centre_id_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_centre_resources')),
    sa.UniqueConstraint('centre_id', 'resource_type', name=op.f('uq_centre_resources_centre_id'))
    )
    op.create_table('farmer_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_farmer_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_farmer_profiles'))
    )
    op.create_table('price_records',
    sa.Column('commodity_id', sa.String(length=36), nullable=False),
    sa.Column('centre_id', sa.String(length=36), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_label', sa.String(length=160), nullable=False),
    sa.Column('illustrative', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('rate > 0', name=op.f('ck_price_records_positive_rate')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_price_records_centre_id_centres')),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], name=op.f('fk_price_records_commodity_id_commodities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_records'))
    )
    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_records_commodity_id'), ['commodity_id'], unique=False)

    op.create_table('staff_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('centre_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_staff_profiles_centre_id_centres')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_staff_profiles')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_staff_profiles_employee_code'))
    )
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_profiles_centre_id'), ['centre_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('bookings',
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('centre_id', sa.String(length=36), nullable=False),
    sa.Column('commodity_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('booked', 'checked_in', 'quality_inspection', 'weighing', 'completed', 'cancelled', name='bookingstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(status = 'cancelled' AND cancelled_at IS NOT NULL) OR (status <> 'cancelled' AND cancelled_at IS NULL AND cancellation_reason IS NULL)", name=op.f('ck_bookings_cancellation_consistency')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_bookings_positive_quantity')),
    sa.CheckConstraint('version > 0', name=op.f('ck_bookings_positive_version')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_bookings_centre_id_centres')),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], name=op.f('fk_bookings_commodity_id_commodities')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.user_id'], name=op.f('fk_bookings_farmer_id_farmer_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('id', 'centre_id', name=op.f('uq_bookings_id')),
    sa.UniqueConstraint('token', name=op.f('uq_bookings_token'))
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_appointment_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_centre_id'), ['centre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('disruptions',
    sa.Column('centre_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.Enum('gate', 'quality_desk', 'weighbridge', 'staff', 'other', name='resourcetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('expected_recovery_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'resolved', name='disruptionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('reported_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("(status = 'active' AND resolved_at IS NULL) OR (status = 'resolved' AND resolved_at IS NOT NULL AND resolved_at >= created_at)", name=op.f('ck_disruptions_resolution_consistency')),
    sa.CheckConstraint('expected_recovery_minutes BETWEEN 5 AND 480', name=op.f('ck_disruptions_recovery_range')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_disruptions_centre_id_centres')),
    sa.ForeignKeyConstraint(['reported_by'], ['staff_profiles.user_id'], name=op.f('fk_disruptions_reported_by_staff_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disruptions'))
    )
    with op.batch_alter_table('disruptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disruptions_centre_id'), ['centre_id'], unique=False)

    op.create_table('booking_group_metadata',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('group_name', sa.String(length=60), nullable=False),
    sa.Column('farmer_count', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=60), nullable=False),
    sa.CheckConstraint('farmer_count BETWEEN 2 AND 20', name=op.f('ck_booking_group_metadata_farmer_count_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_group_metadata_booking_id_bookings')),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('pk_booking_group_metadata'))
    )
    op.create_table('grievances',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('bookings', 'centre', 'quality', 'other', name='grievancecategory', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('centre_id', sa.String(length=36), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'in_review', 'resolved', name='grievancestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_grievances_booking_id_bookings')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_grievances_centre_id_centres')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grievances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grievances')),
    sa.UniqueConstraint('reference', name=op.f('uq_grievances_reference'))
    )
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grievances_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('confirmed', 'reminder', 'queue', 'delay', 'completed', 'grievance', 'cancelled', name='noticetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_notifications_booking_id_bookings')),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('queue_entries',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('centre_id', sa.String(length=36), nullable=False),
    sa.Column('current_stage', sa.Enum('booked', 'checked_in', 'quality_inspection', 'weighing', 'completed', name='queuestage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('held', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('quality_started_at', sa.DateTime(), nullable=True),
    sa.Column('weighing_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('position IS NULL OR position >= 1', name=op.f('ck_queue_entries_positive_position')),
    sa.CheckConstraint('version > 0', name=op.f('ck_queue_entries_positive_version')),
    sa.ForeignKeyConstraint(['booking_id', 'centre_id'], ['bookings.id', 'bookings.centre_id'], name=op.f('fk_queue_entries_booking_id_bookings')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_queue_entries_centre_id_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_entries')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_queue_entries_booking_id'))
    )
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entries_centre_id'), ['centre_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entries_centre_id'))

    op.drop_table('queue_entries')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grievances_user_id'))

    op.drop_table('grievances')
    op.drop_table('booking_group_metadata')
    with op.batch_alter_table('disruptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disruptions_centre_id'))

    op.drop_table('disruptions')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_centre_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_appointment_date'))

    op.drop_table('bookings')
    op.drop_table('user_roles')
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_profiles_centre_id'))

    op.drop_table('staff_profiles')
    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_records_commodity_id'))

    op.drop_table('price_records')
    op.drop_table('farmer_profiles')
    op.drop_table('centre_resources')
    op.drop_table('centre_commodities')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('commodities')
    op.drop_table('centres')
    # ### end Alembic commands ###
