"""identity and slot policies

Revision ID: 0002
Revises: 0001
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('mobile', sa.String(length=10), nullable=False),
    sa.Column('otp_digest', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('attempts BETWEEN 0 AND 5', name=op.f('ck_otp_challenges_attempt_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_mobile'), ['mobile'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_auth_sessions_token_digest'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('slot_policies',
    sa.Column('centre_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_slot_policies_positive_capacity')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_slot_policies_valid_time_range')),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_slot_policies_centre_id_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot_policies')),
    sa.UniqueConstraint('centre_id', 'start_time', name=op.f('uq_slot_policies_centre_id'))
    )
    with op.batch_alter_table('slot_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_policies_centre_id'), ['centre_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_policies_centre_id'))

    op.drop_table('slot_policies')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_mobile'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_created_at'))

    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
