"""staff auth and session assurance

Revision ID: 0003
Revises: 0002
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_auth_attempts',
    sa.Column('identifier_digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('otp_digest', sa.String(length=64), nullable=True),
    sa.Column('credential_digest', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('attempts BETWEEN 0 AND 5', name=op.f('ck_staff_auth_attempts_attempt_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_auth_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_auth_attempts'))
    )
    with op.batch_alter_table('staff_auth_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_auth_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_auth_attempts_identifier_digest'), ['identifier_digest'], unique=False)

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_method', sa.String(length=20), server_default='farmer_otp', nullable=False))
        batch_op.create_check_constraint(op.f('ck_auth_sessions_valid_auth_method'), "auth_method IN ('farmer_otp', 'staff_otp')")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_auth_sessions_valid_auth_method'), type_='check')
        batch_op.drop_column('auth_method')

    with op.batch_alter_table('staff_auth_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_auth_attempts_identifier_digest'))
        batch_op.drop_index(batch_op.f('ix_staff_auth_attempts_created_at'))

    op.drop_table('staff_auth_attempts')
    # ### end Alembic commands ###
