const en = {
  loginTitle: 'Login / Register', loginIntro: 'Your procurement journey starts here.', mobile: 'Mobile number', mobileHint: 'Enter a 10-digit Indian mobile number.', sendOtp: 'Send OTP', newUser: 'New here? The demo opens a fictional farmer profile after verification.', aadhaar: 'Continue with Aadhaar', notConnected: 'Demo only · Not connected', demoNotice: 'Demo access only. No SMS is sent and no real identity is verified.', otpTitle: 'Verify your mobile', otpIntro: 'Enter the demo code for', otpLabel: '6-digit OTP', verify: 'Verify & continue', editMobile: 'Edit mobile number', resend: 'Resend OTP', resendIn: 'Resend available in', seconds: 'seconds', demoCode: 'Demo OTP', wrongOtp: 'That code does not match. Use the demo OTP shown below.', invalidMobile: 'Enter a valid 10-digit mobile number starting with 6–9.', resent: 'Demo code is ready again. No SMS was sent.', sessionWarning: 'Demo access works for this visit, but your browser could not save the session.', farmerAccess: 'Farmer access', stepMobile: '1 · Mobile number', stepOtp: '2 · Verification', profile: 'Demo farmer', location: 'Kollam, Kerala',
}
export type AuthKey = keyof typeof en
const hi: Record<AuthKey,string> = {
 loginTitle:'लॉगिन / पंजीकरण',loginIntro:'आपकी खरीद यात्रा यहाँ शुरू होती है।',mobile:'मोबाइल नंबर',mobileHint:'10 अंकों का भारतीय मोबाइल नंबर दर्ज करें।',sendOtp:'OTP भेजें',newUser:'नए उपयोगकर्ता? सत्यापन के बाद डेमो में एक काल्पनिक किसान प्रोफ़ाइल खुलेगी।',aadhaar:'आधार से जारी रखें',notConnected:'केवल डेमो · जुड़ा नहीं है',demoNotice:'केवल डेमो प्रवेश। कोई SMS नहीं भेजा जाता और वास्तविक पहचान सत्यापित नहीं होती।',otpTitle:'मोबाइल सत्यापित करें',otpIntro:'इस नंबर के लिए डेमो कोड दर्ज करें',otpLabel:'6 अंकों का OTP',verify:'सत्यापित करें और आगे बढ़ें',editMobile:'मोबाइल नंबर बदलें',resend:'OTP फिर भेजें',resendIn:'फिर भेजने के लिए शेष',seconds:'सेकंड',demoCode:'डेमो OTP',wrongOtp:'कोड मेल नहीं खाता। नीचे दिया डेमो OTP इस्तेमाल करें।',invalidMobile:'6–9 से शुरू होने वाला मान्य 10 अंकों का मोबाइल नंबर दर्ज करें।',resent:'डेमो कोड फिर तैयार है। कोई SMS नहीं भेजा गया।',sessionWarning:'इस सत्र में डेमो चलता रहेगा, लेकिन ब्राउज़र सत्र सहेज नहीं पाया।',farmerAccess:'किसान प्रवेश',stepMobile:'1 · मोबाइल नंबर',stepOtp:'2 · सत्यापन',profile:'डेमो किसान',location:'कोल्लम, केरल',
}
const kn: Record<AuthKey,string> = {
 loginTitle:'ಲಾಗಿನ್ / ನೋಂದಣಿ',loginIntro:'ನಿಮ್ಮ ಖರೀದಿ ಪ್ರಯಾಣ ಇಲ್ಲಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.',mobile:'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',mobileHint:'10 ಅಂಕಿಗಳ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.',sendOtp:'OTP ಕಳುಹಿಸಿ',newUser:'ಹೊಸಬರೇ? ಪರಿಶೀಲನೆಯ ನಂತರ ಕಾಲ್ಪನಿಕ ರೈತ ಪ್ರೊಫೈಲ್ ತೆರೆಯುತ್ತದೆ.',aadhaar:'ಆಧಾರ್ ಮೂಲಕ ಮುಂದುವರಿಯಿರಿ',notConnected:'ಡೆಮೊ ಮಾತ್ರ · ಸಂಪರ್ಕಿಸಿಲ್ಲ',demoNotice:'ಡೆಮೊ ಪ್ರವೇಶ ಮಾತ್ರ. SMS ಕಳುಹಿಸುವುದಿಲ್ಲ ಮತ್ತು ನಿಜವಾದ ಗುರುತನ್ನು ಪರಿಶೀಲಿಸುವುದಿಲ್ಲ.',otpTitle:'ಮೊಬೈಲ್ ಪರಿಶೀಲಿಸಿ',otpIntro:'ಈ ಸಂಖ್ಯೆಗೆ ಡೆಮೊ ಕೋಡ್ ನಮೂದಿಸಿ',otpLabel:'6 ಅಂಕಿಗಳ OTP',verify:'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',editMobile:'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬದಲಿಸಿ',resend:'OTP ಮತ್ತೆ ಕಳುಹಿಸಿ',resendIn:'ಮತ್ತೆ ಕಳುಹಿಸಲು ಉಳಿದ ಸಮಯ',seconds:'ಸೆಕೆಂಡುಗಳು',demoCode:'ಡೆಮೊ OTP',wrongOtp:'ಕೋಡ್ ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ. ಕೆಳಗಿನ ಡೆಮೊ OTP ಬಳಸಿ.',invalidMobile:'6–9 ರಿಂದ ಪ್ರಾರಂಭವಾಗುವ ಮಾನ್ಯ 10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.',resent:'ಡೆಮೊ ಕೋಡ್ ಮತ್ತೆ ಸಿದ್ಧವಾಗಿದೆ. SMS ಕಳುಹಿಸಿಲ್ಲ.',sessionWarning:'ಈ ಭೇಟಿಯಲ್ಲಿ ಡೆಮೊ ಲಭ್ಯವಿದೆ, ಆದರೆ ಬ್ರೌಸರ್ ಅಧಿವೇಶನವನ್ನು ಉಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',farmerAccess:'ರೈತರ ಪ್ರವೇಶ',stepMobile:'1 · ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',stepOtp:'2 · ಪರಿಶೀಲನೆ',profile:'ಡೆಮೊ ರೈತ',location:'ಕೊಲ್ಲಂ, ಕೇರಳ',
}
const ta: Record<AuthKey,string> = {
 loginTitle:'உள்நுழைவு / பதிவு',loginIntro:'உங்கள் கொள்முதல் பயணம் இங்கே தொடங்குகிறது.',mobile:'மொபைல் எண்',mobileHint:'10 இலக்க இந்திய மொபைல் எண்ணை உள்ளிடவும்.',sendOtp:'OTP அனுப்பவும்',newUser:'புதியவரா? சரிபார்ப்புக்குப் பின் கற்பனை விவசாயி சுயவிவரம் திறக்கும்.',aadhaar:'ஆதார் மூலம் தொடரவும்',notConnected:'செயல்விளக்கம் மட்டும் · இணைக்கப்படவில்லை',demoNotice:'செயல்விளக்க அணுகல் மட்டும். SMS அனுப்பப்படாது; உண்மையான அடையாளம் சரிபார்க்கப்படாது.',otpTitle:'மொபைலைச் சரிபார்க்கவும்',otpIntro:'இந்த எண்ணிற்கான செயல்விளக்கக் குறியீட்டை உள்ளிடவும்',otpLabel:'6 இலக்க OTP',verify:'சரிபார்த்துத் தொடரவும்',editMobile:'மொபைல் எண்ணை மாற்றவும்',resend:'OTP மீண்டும் அனுப்பவும்',resendIn:'மீண்டும் அனுப்ப மீதமுள்ள நேரம்',seconds:'விநாடிகள்',demoCode:'செயல்விளக்க OTP',wrongOtp:'குறியீடு பொருந்தவில்லை. கீழே உள்ள செயல்விளக்க OTP பயன்படுத்தவும்.',invalidMobile:'6–9 இல் தொடங்கும் செல்லுபடியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.',resent:'செயல்விளக்கக் குறியீடு மீண்டும் தயார். SMS அனுப்பப்படவில்லை.',sessionWarning:'இந்த வருகைக்கு அணுகல் உள்ளது; உலாவியால் அமர்வைச் சேமிக்க முடியவில்லை.',farmerAccess:'விவசாயி அணுகல்',stepMobile:'1 · மொபைல் எண்',stepOtp:'2 · சரிபார்ப்பு',profile:'செயல்விளக்க விவசாயி',location:'கொல்லம், கேரளா',
}
const ml: Record<AuthKey,string> = {
 loginTitle:'ലോഗിൻ / രജിസ്ട്രേഷൻ',loginIntro:'നിങ്ങളുടെ സംഭരണ യാത്ര ഇവിടെ തുടങ്ങുന്നു.',mobile:'മൊബൈൽ നമ്പർ',mobileHint:'10 അക്ക ഇന്ത്യൻ മൊബൈൽ നമ്പർ നൽകുക.',sendOtp:'OTP അയയ്ക്കുക',newUser:'പുതിയ ഉപയോക്താവാണോ? പരിശോധനയ്ക്കുശേഷം സാങ്കൽപ്പിക കർഷക പ്രൊഫൈൽ തുറക്കും.',aadhaar:'ആധാർ ഉപയോഗിച്ച് തുടരുക',notConnected:'ഡെമോ മാത്രം · ബന്ധിപ്പിച്ചിട്ടില്ല',demoNotice:'ഡെമോ പ്രവേശനം മാത്രം. SMS അയയ്ക്കുന്നില്ല; യഥാർത്ഥ തിരിച്ചറിയൽ പരിശോധിക്കുന്നില്ല.',otpTitle:'മൊബൈൽ പരിശോധിക്കുക',otpIntro:'ഈ നമ്പറിനുള്ള ഡെമോ കോഡ് നൽകുക',otpLabel:'6 അക്ക OTP',verify:'പരിശോധിച്ച് തുടരുക',editMobile:'മൊബൈൽ നമ്പർ മാറ്റുക',resend:'OTP വീണ്ടും അയയ്ക്കുക',resendIn:'വീണ്ടും അയയ്ക്കാൻ ശേഷിക്കുന്നത്',seconds:'സെക്കൻഡ്',demoCode:'ഡെമോ OTP',wrongOtp:'കോഡ് പൊരുത്തപ്പെടുന്നില്ല. താഴെയുള്ള ഡെമോ OTP ഉപയോഗിക്കുക.',invalidMobile:'6–9 ൽ തുടങ്ങുന്ന സാധുവായ 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക.',resent:'ഡെമോ കോഡ് വീണ്ടും തയ്യാറാണ്. SMS അയച്ചിട്ടില്ല.',sessionWarning:'ഈ സന്ദർശനത്തിൽ ഡെമോ ലഭ്യമാണ്; ബ്രൗസറിന് സെഷൻ സൂക്ഷിക്കാനായില്ല.',farmerAccess:'കർഷക പ്രവേശനം',stepMobile:'1 · മൊബൈൽ നമ്പർ',stepOtp:'2 · പരിശോധന',profile:'ഡെമോ കർഷകൻ',location:'കൊല്ലം, കേരളം',
}
export const authTranslations = { en, hi, kn, ta, ml }
