const en = {
  farmerHome: 'Farmer home', welcomeFarmer: 'Welcome, Ravi', homeIntro: 'Plan your visit. Keep your procurement on track.', bookSlot: 'Book a Slot', myBookings: 'My Bookings', findCentre: 'Find a Centre', groupBooking: 'Group Booking', recommended: 'Recommended for you', bestOption: 'Best Option', centreKollam: 'Kollam Procurement Centre', travel: 'Estimated travel', currentWait: 'Current wait', minutes: 'min', kilometres: 'km', viewCentre: 'View Centre', otherCentres: 'Find Other Centres', upcoming: 'Your upcoming booking', tokenLabel: 'Token', paddy: 'Paddy', commodity: 'Commodity', appointment: 'Date & time', onSchedule: 'On Schedule', viewStatus: 'View Status', quickInfo: 'Information & support', prices: 'Price Information', schemes: 'Government Schemes', guide: 'Farmer Guide', support: 'Support / Help', bookingsNav: 'Bookings', liveStatus: 'Live Status', more: 'More', services: 'More services', market: 'Market Updates', grievance: 'Grievance', chat: 'Chat with Us', settings: 'Settings', logout: 'Logout', profileMenu: 'Profile menu', profileDetails: 'Profile', notificationLabel: 'Notifications', demoFixture: 'Sample demo data · Not a live booking or recommendation', recommendationNote: 'Illustrative best option. Live recommendations will be available later.', comingSoon: 'Coming in the next demo step', placeholderText: 'This service is a preview. No request will be submitted.', allServices: 'View all services', logoutError: 'The saved demo session could not be cleared. Please try logout again.', navLabel: 'Farmer navigation', sampleProfile: 'Fictional demo profile',
}
export type HomeKey = keyof typeof en
const hi: Record<HomeKey,string> = {
 farmerHome:'किसान होम',welcomeFarmer:'स्वागत है, रवि',homeIntro:'अपनी यात्रा की योजना बनाएँ। खरीद की प्रगति जानें।',bookSlot:'स्लॉट बुक करें',myBookings:'मेरी बुकिंग',findCentre:'केंद्र खोजें',groupBooking:'समूह बुकिंग',recommended:'आपके लिए सुझाव',bestOption:'बेहतर विकल्प',centreKollam:'कोल्लम खरीद केंद्र',travel:'अनुमानित यात्रा',currentWait:'वर्तमान प्रतीक्षा',minutes:'मिनट',kilometres:'किमी',viewCentre:'केंद्र देखें',otherCentres:'अन्य केंद्र खोजें',upcoming:'आपकी आगामी बुकिंग',tokenLabel:'टोकन',paddy:'धान',commodity:'उपज',appointment:'तारीख और समय',onSchedule:'समय पर',viewStatus:'स्थिति देखें',quickInfo:'जानकारी और सहायता',prices:'मूल्य जानकारी',schemes:'सरकारी योजनाएँ',guide:'किसान मार्गदर्शिका',support:'सहायता / मदद',bookingsNav:'बुकिंग',liveStatus:'वर्तमान स्थिति',more:'और',services:'अन्य सेवाएँ',market:'बाज़ार समाचार',grievance:'शिकायत',chat:'हमसे बात करें',settings:'सेटिंग्स',logout:'लॉगआउट',profileMenu:'प्रोफ़ाइल मेनू',profileDetails:'प्रोफ़ाइल',notificationLabel:'सूचनाएँ',demoFixture:'नमूना डेमो डेटा · वास्तविक बुकिंग या सुझाव नहीं',recommendationNote:'केवल उदाहरण। वास्तविक सुझाव बाद में उपलब्ध होंगे।',comingSoon:'अगले डेमो चरण में उपलब्ध',placeholderText:'यह सेवा केवल पूर्वावलोकन है। कोई अनुरोध जमा नहीं होगा।',allServices:'सभी सेवाएँ देखें',logoutError:'सहेजा हुआ डेमो सत्र हट नहीं पाया। फिर लॉगआउट करें।',navLabel:'किसान नेविगेशन',sampleProfile:'काल्पनिक डेमो प्रोफ़ाइल',
}
const kn: Record<HomeKey,string> = {
 farmerHome:'ರೈತರ ಮುಖಪುಟ',welcomeFarmer:'ಸ್ವಾಗತ, ರವಿ',homeIntro:'ನಿಮ್ಮ ಭೇಟಿಯನ್ನು ಯೋಜಿಸಿ. ಖರೀದಿಯ ಪ್ರಗತಿಯನ್ನು ತಿಳಿಯಿರಿ.',bookSlot:'ಸಮಯ ಕಾಯ್ದಿರಿಸಿ',myBookings:'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',findCentre:'ಕೇಂದ್ರ ಹುಡುಕಿ',groupBooking:'ಗುಂಪು ಬುಕಿಂಗ್',recommended:'ನಿಮಗಾಗಿ ಶಿಫಾರಸು',bestOption:'ಉತ್ತಮ ಆಯ್ಕೆ',centreKollam:'ಕೊಲ್ಲಂ ಖರೀದಿ ಕೇಂದ್ರ',travel:'ಅಂದಾಜು ಪ್ರಯಾಣ',currentWait:'ಪ್ರಸ್ತುತ ಕಾಯುವಿಕೆ',minutes:'ನಿಮಿಷ',kilometres:'ಕಿಮೀ',viewCentre:'ಕೇಂದ್ರ ನೋಡಿ',otherCentres:'ಇತರ ಕೇಂದ್ರಗಳನ್ನು ಹುಡುಕಿ',upcoming:'ನಿಮ್ಮ ಮುಂದಿನ ಬುಕಿಂಗ್',tokenLabel:'ಟೋಕನ್',paddy:'ಭತ್ತ',commodity:'ಬೆಳೆ',appointment:'ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',onSchedule:'ನಿಗದಿತ ಸಮಯದಲ್ಲಿ',viewStatus:'ಸ್ಥಿತಿ ನೋಡಿ',quickInfo:'ಮಾಹಿತಿ ಮತ್ತು ಸಹಾಯ',prices:'ಬೆಲೆ ಮಾಹಿತಿ',schemes:'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',guide:'ರೈತರ ಮಾರ್ಗದರ್ಶಿ',support:'ಬೆಂಬಲ / ಸಹಾಯ',bookingsNav:'ಬುಕಿಂಗ್‌ಗಳು',liveStatus:'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ',more:'ಇನ್ನಷ್ಟು',services:'ಇನ್ನಷ್ಟು ಸೇವೆಗಳು',market:'ಮಾರುಕಟ್ಟೆ ಸುದ್ದಿ',grievance:'ದೂರು',chat:'ನಮ್ಮೊಂದಿಗೆ ಮಾತನಾಡಿ',settings:'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',logout:'ಲಾಗ್ ಔಟ್',profileMenu:'ಪ್ರೊಫೈಲ್ ಮೆನು',profileDetails:'ಪ್ರೊಫೈಲ್',notificationLabel:'ಅಧಿಸೂಚನೆಗಳು',demoFixture:'ಮಾದರಿ ಡೆಮೊ ಡೇಟಾ · ನೈಜ ಬುಕಿಂಗ್ ಅಥವಾ ಶಿಫಾರಸು ಅಲ್ಲ',recommendationNote:'ಉದಾಹರಣೆಯ ಆಯ್ಕೆ. ನೇರ ಶಿಫಾರಸುಗಳು ನಂತರ ಲಭ್ಯವಾಗುತ್ತವೆ.',comingSoon:'ಮುಂದಿನ ಡೆಮೊ ಹಂತದಲ್ಲಿ ಲಭ್ಯ',placeholderText:'ಇದು ಸೇವೆಯ ಪೂರ್ವವೀಕ್ಷಣೆ. ಯಾವುದೇ ವಿನಂತಿ ಸಲ್ಲಿಸುವುದಿಲ್ಲ.',allServices:'ಎಲ್ಲ ಸೇವೆಗಳನ್ನು ನೋಡಿ',logoutError:'ಉಳಿಸಿದ ಡೆಮೊ ಅಧಿವೇಶನವನ್ನು ತೆರವುಗೊಳಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಲಾಗ್ ಔಟ್ ಮಾಡಿ.',navLabel:'ರೈತರ ನ್ಯಾವಿಗೇಷನ್',sampleProfile:'ಕಾಲ್ಪನಿಕ ಡೆಮೊ ಪ್ರೊಫೈಲ್',
}
const ta: Record<HomeKey,string> = {
 farmerHome:'விவசாயி முகப்பு',welcomeFarmer:'வரவேற்கிறோம், ரவி',homeIntro:'உங்கள் வருகையைத் திட்டமிடுங்கள். கொள்முதல் நிலையை அறியுங்கள்.',bookSlot:'நேரம் முன்பதிவு',myBookings:'எனது முன்பதிவுகள்',findCentre:'மையத்தைத் தேடு',groupBooking:'குழு முன்பதிவு',recommended:'உங்களுக்கான பரிந்துரை',bestOption:'சிறந்த தேர்வு',centreKollam:'கொல்லம் கொள்முதல் மையம்',travel:'பயண நேர மதிப்பீடு',currentWait:'தற்போதைய காத்திருப்பு',minutes:'நிமிடம்',kilometres:'கிமீ',viewCentre:'மையத்தைப் பார்',otherCentres:'பிற மையங்களைத் தேடு',upcoming:'உங்கள் அடுத்த முன்பதிவு',tokenLabel:'டோக்கன்',paddy:'நெல்',commodity:'விளைபொருள்',appointment:'தேதி மற்றும் நேரம்',onSchedule:'திட்டமிட்டபடி',viewStatus:'நிலையைப் பார்',quickInfo:'தகவல் மற்றும் உதவி',prices:'விலைத் தகவல்',schemes:'அரசுத் திட்டங்கள்',guide:'விவசாயி வழிகாட்டி',support:'ஆதரவு / உதவி',bookingsNav:'முன்பதிவுகள்',liveStatus:'தற்போதைய நிலை',more:'மேலும்',services:'மேலும் சேவைகள்',market:'சந்தைச் செய்திகள்',grievance:'புகார்',chat:'எங்களுடன் பேசுங்கள்',settings:'அமைப்புகள்',logout:'வெளியேறு',profileMenu:'சுயவிவர மெனு',profileDetails:'சுயவிவரம்',notificationLabel:'அறிவிப்புகள்',demoFixture:'மாதிரி தரவு · உண்மையான முன்பதிவு அல்லது பரிந்துரை அல்ல',recommendationNote:'எடுத்துக்காட்டு தேர்வு. நேரடி பரிந்துரைகள் பின்னர் கிடைக்கும்.',comingSoon:'அடுத்த செயல்விளக்கப் படியில் கிடைக்கும்',placeholderText:'இது சேவை முன்னோட்டம். கோரிக்கை எதுவும் அனுப்பப்படாது.',allServices:'அனைத்துச் சேவைகளும்',logoutError:'சேமித்த அமர்வை நீக்க முடியவில்லை. மீண்டும் வெளியேற முயலவும்.',navLabel:'விவசாயி வழிசெலுத்தல்',sampleProfile:'கற்பனை செயல்விளக்க சுயவிவரம்',
}
const ml: Record<HomeKey,string> = {
 farmerHome:'കർഷക മുഖപ്പേജ്',welcomeFarmer:'സ്വാഗതം, രവി',homeIntro:'സന്ദർശനം ആസൂത്രണം ചെയ്യൂ. സംഭരണ പുരോഗതി അറിയൂ.',bookSlot:'സ്ലോട്ട് ബുക്ക് ചെയ്യുക',myBookings:'എന്റെ ബുക്കിങ്ങുകൾ',findCentre:'കേന്ദ്രം കണ്ടെത്തുക',groupBooking:'ഗ്രൂപ്പ് ബുക്കിങ്',recommended:'നിങ്ങൾക്കുള്ള ശുപാർശ',bestOption:'മികച്ച ഓപ്ഷൻ',centreKollam:'കൊല്ലം സംഭരണ കേന്ദ്രം',travel:'ഏകദേശ യാത്രാസമയം',currentWait:'നിലവിലെ കാത്തിരിപ്പ്',minutes:'മിനിറ്റ്',kilometres:'കി.മീ.',viewCentre:'കേന്ദ്രം കാണുക',otherCentres:'മറ്റ് കേന്ദ്രങ്ങൾ കണ്ടെത്തുക',upcoming:'നിങ്ങളുടെ അടുത്ത ബുക്കിങ്',tokenLabel:'ടോക്കൺ',paddy:'നെല്ല്',commodity:'വിള',appointment:'തീയതിയും സമയവും',onSchedule:'സമയക്രമപ്രകാരം',viewStatus:'നില കാണുക',quickInfo:'വിവരങ്ങളും സഹായവും',prices:'വില വിവരങ്ങൾ',schemes:'സർക്കാർ പദ്ധതികൾ',guide:'കർഷക മാർഗദർശി',support:'പിന്തുണ / സഹായം',bookingsNav:'ബുക്കിങ്ങുകൾ',liveStatus:'നിലവിലെ നില',more:'കൂടുതൽ',services:'കൂടുതൽ സേവനങ്ങൾ',market:'വിപണി വാർത്തകൾ',grievance:'പരാതി',chat:'ഞങ്ങളോട് സംസാരിക്കുക',settings:'ക്രമീകരണങ്ങൾ',logout:'ലോഗൗട്ട്',profileMenu:'പ്രൊഫൈൽ മെനു',profileDetails:'പ്രൊഫൈൽ',notificationLabel:'അറിയിപ്പുകൾ',demoFixture:'സാമ്പിൾ ഡെമോ ഡാറ്റ · യഥാർത്ഥ ബുക്കിങ്ങോ ശുപാർശയോ അല്ല',recommendationNote:'ഉദാഹരണമായ മികച്ച ഓപ്ഷൻ. തത്സമയ ശുപാർശകൾ പിന്നീട് ലഭ്യമാകും.',comingSoon:'അടുത്ത ഡെമോ ഘട്ടത്തിൽ ലഭ്യമാകും',placeholderText:'ഇത് സേവനത്തിന്റെ മാതൃകയാണ്. അഭ്യർത്ഥന അയയ്ക്കില്ല.',allServices:'എല്ലാ സേവനങ്ങളും കാണുക',logoutError:'സൂക്ഷിച്ച ഡെമോ സെഷൻ നീക്കാനായില്ല. വീണ്ടും ലോഗൗട്ട് ചെയ്യുക.',navLabel:'കർഷക നാവിഗേഷൻ',sampleProfile:'സാങ്കൽപ്പിക ഡെമോ പ്രൊഫൈൽ',
}
export const homeTranslations = { en, hi, kn, ta, ml }
